language: go
go:
  - 1.10.x
go_import_path: github.com/teamwork/guru
notifications:
  email: false
  webhooks: https://tw-bot.eu.teamworkops.com/travis/buildstatus
cache:
  directories:
    - $HOME/.cache/go-build
install:
  - ./bin/setup-travis
script:
  - cd $HOME/gopath/src/github.com/teamwork/guru
  - ./bin/test -race ./...
  - ./bin/coverage
  - ./bin/lint ./...
