language: go
go:
  - 1.13.x
go_import_path: github.com/teamwork/guru
notifications:
  email: false
  webhooks: https://tw-bot.eu.teamworkops.com/travis/buildstatus
cache:
  directories:
    - $HOME/.cache/go-build
install:
script: |
  export GO111MODULE=on
  GO111MODULE=off go get github.com/golangci/golangci-lint/cmd/golangci-lint
  golangci-lint run ./...
  go test -race \
    -coverprofile=coverage.txt \
    -coverpkg=./... \
    ./...
  bash <(curl -s https://codecov.io/bash)
